# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - master
      - v2
      - feature/**
  pull_request:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # Chromatic project token (to be added as GitHub secret)
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Build Storybook
          buildScriptName: build-storybook
          # Exit with error on visual changes (optional, remove if you want manual approval)
          # exitOnceUploaded: true
          # Auto-accept changes on master branch
          autoAcceptChanges: "master"
