# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - master
      - v2
      - feature/**
  pull_request:

# Minimal permissions for security (least-privilege principle)
permissions:
  contents: read

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Concurrency group to cancel in-progress runs for the same branch/PR
    concurrency:
      group: chromatic-${{ github.ref }}
      cancel-in-progress: true
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # Chromatic project token (to be added as GitHub secret)
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Build Storybook
          buildScriptName: build-storybook
          # exitOnceUploaded ends the job after upload and does not control failure on visual diffs.
          # If you want the job not to fail on visual diffs, use exitZeroOnChanges: true.
          # If you want the job to return early after upload, keep exitOnceUploaded: true.
          # exitOnceUploaded: true
          # Auto-accept changes only on master branch
          autoAcceptChanges: ${{ github.ref_name == 'master' }}
