name: Audit Accessibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build Storybook
        run: npm run build-storybook
      - name: Serve Storybook
        run: npx serve ./storybook-static -l 8080 &
      - name: Wait for server
        run: npx wait-on http://localhost:8080
      - name: Run Lighthouse (HTML & JSON)
        run: |
          npx lighthouse http://localhost:8080 --output html --output-path ./storybook-static/lighthouse-report.html --chrome-flags="--headless"
          npx lighthouse http://localhost:8080 --output json --output-path ./storybook-static/lighthouse-report.json --chrome-flags="--headless"
      - name: Copy Lighthouse report to docs for GitHub Pages
        run: cp ./storybook-static/lighthouse-report.html ./docs/lighthouse-report.html
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            ./storybook-static/lighthouse-report.html
            ./storybook-static/lighthouse-report.json
            ./docs/lighthouse-report.html
      - name: Update accessibility badge in README
        run: node update-badge.js
